import React, { useState, useCallback } from 'react';
import { ReportData } from './types';
import { generateInvestmentProposal } from './services/geminiService';
import Loader from './components/Loader';
import CompetitionChart from './components/CompetitionChart';
import { NebulaXLogo, ChimeraLogo, HNBLogo, NebulaLogo } from './components/Logos';
import {
  DocumentTextIcon,
  AcademicCapIcon,
  ChartBarIcon,
  UserIcon,
  SparklesIcon,
  LightBulbIcon,
  CpuChipIcon,
  LinkIcon
} from '@heroicons/react/24/outline';


const Section: React.FC<{ title: string; icon: React.ReactNode; children: React.ReactNode }> = ({ title, icon, children }) => (
  <section className="mb-12 bg-gray-900/50 p-6 sm:p-8 rounded-2xl border border-gray-700/50 backdrop-blur-sm shadow-2xl shadow-black/20">
    <div className="flex items-center mb-6">
      <div className="bg-indigo-500/10 text-indigo-400 p-3 rounded-xl mr-4 border border-indigo-500/20">{icon}</div>
      <h2 className="text-3xl font-bold text-white tracking-tight">{title}</h2>
    </div>
    <div className="prose prose-invert max-w-none prose-p:text-gray-300 prose-li:text-gray-300">
      {children}
    </div>
  </section>
);

const getProjectLogo = (projectName: string) => {
  switch (projectName.toLowerCase()) {
    case 'chimera':
      return <ChimeraLogo className="h-10 w-10 text-indigo-400" />;
    case 'hnb (holographic neuromorphic brain)':
       return <HNBLogo className="h-10 w-10 text-purple-400" />;
    case 'nebula project suite':
      return <NebulaLogo className="h-10 w-10 text-sky-400" />;
    default:
      return <CpuChipIcon className="h-10 w-10 text-gray-500" />;
  }
};


const App: React.FC = () => {
  const [reportData, setReportData] = useState<ReportData | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [loadingMessage, setLoadingMessage] = useState<string>('');
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    setReportData(null);

    try {
      const data = await generateInvestmentProposal(setLoadingMessage);
      setReportData(data);
    } catch (e) {
      console.error(e);
      setError(e instanceof Error ? e.message : "An unknown error occurred.");
    } finally {
      setIsLoading(false);
    }
  }, []);

  const renderInitialState = () => (
    <div className="text-center">
      <div className="max-w-3xl mx-auto">
         <NebulaXLogo className="h-20 mx-auto mb-6" />
         <h1 className="text-5xl md:text-6xl font-black text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-indigo-500 tracking-tighter">
          Technical Capabilities Report Generator
        </h1>
        <p className="mt-6 text-lg text-gray-300">
          Utilizing Gemini 2.5 Pro to conduct a deep analysis of research papers, source code, and performance benchmarks to generate a comprehensive and professional capabilities report.
        </p>
      </div>
      <button
        onClick={handleGenerate}
        disabled={isLoading}
        className="mt-12 px-8 py-4 bg-indigo-600 text-white font-bold text-lg rounded-lg hover:bg-indigo-500 transition-all duration-300 transform hover:scale-105 shadow-lg shadow-indigo-600/30"
      >
        {isLoading ? 'Generating...' : 'Generate Report'}
      </button>
    </div>
  );

  const renderReport = () => {
    if (!reportData) return null;

    return (
      <div className="max-w-5xl mx-auto">
        <header className="text-center mb-16 border-b border-gray-700/50 pb-8">
          <NebulaXLogo className="h-24 mx-auto mb-4" />
          <h1 className="text-4xl md:text-5xl font-black text-white tracking-tight">
            {reportData.title}
          </h1>
          <p className="mt-4 text-lg text-gray-500">Generated by Gemini 2.5 Pro</p>
        </header>

        <Section title="Executive Summary" icon={<DocumentTextIcon className="w-6 h-6" />}>
          <p>{reportData.executiveSummary}</p>
        </Section>
        
        <Section title="Vision Statement" icon={<LightBulbIcon className="w-6 h-6" />}>
          <p className="text-xl italic text-indigo-300 border-l-4 border-indigo-400 pl-6">{reportData.visionStatement}</p>
        </Section>

        <Section title="Core Technology Portfolio" icon={<CpuChipIcon className="w-6 h-6" />}>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {reportData.technologyPortfolio.map((project, index) => (
              <div key={index} className="bg-gray-800/60 p-6 rounded-xl border border-gray-700 flex flex-col transition-all duration-300 hover:border-indigo-500/50 hover:bg-gray-800">
                <div className="flex items-center gap-4 mb-4">
                  {getProjectLogo(project.name)}
                  <h3 className="text-xl font-bold text-indigo-400">{project.name}</h3>
                </div>
                <p className="mt-2 text-sm text-gray-300 flex-grow">{project.description}</p>
                <ul className="mt-4 space-y-2 text-sm">
                  {project.keyFeatures.map((feature, i) => <li key={i} className="flex items-center"><SparklesIcon className="w-4 h-4 mr-2 text-purple-400 shrink-0" />{feature}</li>)}
                </ul>
                <a href={project.url} target="_blank" rel="noopener noreferrer" className="mt-6 text-sm text-indigo-400 hover:text-indigo-300 flex items-center self-start font-semibold">
                  View Repository <LinkIcon className="w-4 h-4 ml-1" />
                </a>
              </div>
            ))}
          </div>
        </section>

        <Section title="Research & Publications" icon={<AcademicCapIcon className="w-6 h-6" />}>
          <div className="space-y-6">
            {reportData.researchTraction.map((pub, index) => (
              <div key={index} className="bg-gray-800/60 p-4 rounded-lg border border-gray-700">
                <h4 className="font-bold text-purple-400">{pub.title}</h4>
                <p className="text-sm mt-1">{pub.summary}</p>
                <p className="text-xs text-gray-500 mt-2">{pub.publicationDate}</p>
              </div>
            ))}
          </div>
        </Section>
        
        <Section title="Industry & Research Landscape" icon={<ChartBarIcon className="w-6 h-6" />}>
           <p>{reportData.marketAnalysis.summary}</p>
           {reportData.marketAnalysis.sources.length > 0 && (
             <div className="mt-6 pt-4 border-t border-gray-700/50">
                <h4 className="font-semibold text-gray-100">Sources:</h4>
                <ul className="list-disc pl-5 mt-2 space-y-1 text-sm">
                  {reportData.marketAnalysis.sources.map((source, index) => (
                    <li key={index}>
                      <a href={source.uri} target="_blank" rel="noopener noreferrer" className="text-indigo-400 hover:underline">{source.title}</a>
                    </li>
                  ))}
                </ul>
             </div>
           )}
        </Section>

        <Section title="Competitive Performance Validation" icon={<ChartBarIcon className="w-6 h-6" />}>
          <p className="mb-6">Performance across various machine learning and AI competitions demonstrates a strong capability to deliver results in diverse and challenging domains. The chart below visualizes the percentile rank in competitions with numerical placements, showcasing consistent high-percentile performance.</p>
          <CompetitionChart data={reportData.performanceValidation} />
        </Section>
        
        <Section title="Principal Researcher" icon={<UserIcon className="w-6 h-6" />}>
          <h3 className="text-2xl font-bold text-indigo-400">{reportData.team.name}</h3>
          <p className="text-lg text-gray-400">{reportData.team.title}</p>
          <p className="mt-4">{reportData.team.bio}</p>
        </Section>
      </div>
    );
  };
  

  return (
    <div className="bg-gray-900 min-h-screen text-gray-200">
      <div className="relative isolate min-h-screen flex items-center justify-center p-4 sm:p-6 lg:p-8">
        <div 
          className="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80" 
          aria-hidden="true">
          <div 
            className="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-20 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]" 
            style={{
              clipPath: 'polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)'
            }}
          ></div>
        </div>
        
        {error && <div className="text-red-400 bg-red-900/50 p-4 rounded-lg">Error: {error}</div>}
        {isLoading && <Loader message={loadingMessage} />}
        {!isLoading && !reportData && !error && renderInitialState()}
        {reportData && renderReport()}

      </div>
    </div>
  );
};

export default App;
